FROM golang:1.10 as build_image
ARG LDFLAGS
RUN apt install python
RUN mkdir -p /app/data

WORKDIR /app
ADD . /app
RUN ./build.sh
RUN chmod +x ./start.sh

EXPOSE 8081
EXPOSE 9851
CMD ["/app/start.sh"]
