FROM alpine:3.8
RUN apk add --no-cache ca-certificates python bash

ADD tile38-server /usr/local/bin
ADD tile38-cli /usr/local/bin
ADD start.sh /usr/local/bin
RUN chmod +x /usr/local/bin/start.sh

RUN addgroup -S tile38 && \
    adduser -S -G tile38 tile38 && \
    mkdir /data && chown tile38:tile38 /data

ADD data/* /data/

EXPOSE 8081
EXPOSE 9851
CMD ["start.sh"]
